### ISSUE TITLE
SLSQP

### ISSUE THREAD

**Issue by zaikunzhang** [ragonneau/phd-thesis#42]
See my email. Merci.

**Comment by ragonneau** [comment]
* The mistake in the citations of `Schittkowski_1981a` and `Schittkowski_1981b` is corrected.
* We should mention SLSQP in 4.4 Software based on the SQP method. SLSQP (Sequential Least-Squares Quadratic Programming, Kraft_1988) is included in SciPy. Note that it is a solver for general problems, not only for LS. The "LSQP"  in the name means that the QP subproblem is formulated as a least squares problem (with constraints). This formulation is due to Schitkowski_1981b (see Sec 3 of Schittkowski_1981b and Sec 2.2.5 of Kraft_1988). It requires that the approximate Hessian is positive definite, which is commonly implemented by the damped BFGS update of Powell.
